version: '3.8'
services:
  app:
    image: angular-image:1.0
    ports:
      - 4200:4200
    networks:
      - portfolio
  backend:
    image: backend-image
    ports:
      - 4000:4000
    environment:
      - RAILS_MASTER_KEY=9082a5be5e98bc556999e39e8a3dab3f
      - DATABASE_URL=postgresql://postgres:123HotelCalifornia.@db:5432/capstone_project_back_end
    networks:
      - portfolio
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123HotelCalifornia.
    networks:
      - portfolio
    ports:
      - 5432:5432
networks:
  portfolio:
